version: "3.9"
services:
  app:
    build: .
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/python_fan_control
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always